services:
  cc-lms-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cc-lms-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
